CREATE TABLE IF NOT EXISTS KATEGORIES (
   ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   NAME VARCHAR(255) NOT NULL,
   UNIQUE(ID, NAME)
);

CREATE TABLE IF NOT EXISTS PRODUKT (
   ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   NAME VARCHAR(255),
   PRICE INT,
   PRODUKT_SIZE INT,
   KATEGORY_ID INT,
   FOREIGN KEY (KATEGORY_ID) REFERENCES KATEGORIES(ID)
);

CREATE TABLE IF NOT EXISTS OWNER (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255)
);


CREATE TABLE IF NOT EXISTS STORE (
   ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   NAME VARCHAR(255),
   OWNER_ID INT,
   FOREIGN KEY (OWNER_ID) REFERENCES OWNER(ID)
);
